"""init schema

Revision ID: 28791a120f43
Revises: 
Create Date: 2026-03-16 18:05:40.371801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28791a120f43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('naver_place_id', sa.String(), nullable=True),
    sa.Column('google_place_id', sa.String(), nullable=True),
    sa.Column('gangnamunni_id', sa.String(), nullable=True),
    sa.Column('crawl_interval_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_index(op.f('ix_hospitals_hospital_id'), 'hospitals', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospitals_tenant_id'), 'hospitals', ['tenant_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('naver', 'google', 'gangnamunni', name='platform'), nullable=False),
    sa.Column('platform_review_id', sa.String(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('visitor_name', sa.String(), nullable=True),
    sa.Column('visited_date', sa.String(), nullable=True),
    sa.Column('sentiment', sa.Enum('positive', 'negative', 'neutral', name='sentiment'), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('reply_status', sa.Enum('pending', 'approved', 'posted', name='replystatus'), nullable=True),
    sa.Column('reply_style', sa.Enum('formal', 'friendly', 'positive', name='replystyle'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_hospital_id'), 'reviews', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_platform_review_id'), 'reviews', ['platform_review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_platform_review_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_hospital_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_hospitals_tenant_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_hospital_id'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
